### ISSUE TITLE
Add Ottawa health region data for total_vaccinated and total_vaccines_distributed

### ISSUE THREAD

**Issue by colinbendell** [andrewthong/covid19tracker-api#66]
The Ottawa health region is reporting fully vaccinated and total vaccines distributed at `https://www.ottawapublichealth.ca/en/reports-research-and-statistics/daily-covid19-dashboard.aspx` (under Vaccination & Testing). Currently they are reporting 97,170 doses received, 87,737 doses administered

**Comment by noahlittle** [comment]
As only a small percentage (<5%) of health regions are providing or are anticipated to provide vaccine distribution data, we do not anticipate the addition of distribution data for regions.

We include total_vaccinated for the health regions that report this data. Ottawa only reports the total number of doses administered and does not have data available for total_vaccinated.

**Comment by colinbendell** [comment]
I can't tell if your resistance to adjusting your schema to collect more and richer data is grounded in pragmatism or grounded in avoidance. There is already inconsistency (because of the nature of the reporting) at the region / zone level. Adjusting the schema to match the province level would just enable support for the necessary data to be augmented. 

I'm [already augmenting your data](https://raw.githubusercontent.com/colinbendell/covid19data.ca/main/data.json) with [external](https://github.com/colinbendell/covid19data.ca/blob/main/statscanada-hr2017.json#L115-L125) sources out of your resistance to expand and [normalize](https://github.com/colinbendell/covid19data.ca/blob/main/index.js#L126) your schema which feels a shame. You have the potential of having the authoritative data distribution point - you just need a more extensible schema. There is deep data opportunities if you start combining this with demographic data, acceleration rates for incidents and vaccine distribution, etc.

**Comment by noahlittle** [comment]
Much of the issue with expanding data collected surrounds the fact that all of the data is collected manually, every day, by a very small team of volunteers that's already stretched thin. Adding an additional datapoint (which applies to very few health regions) would increase the complexity of the daily workflow, and provide an additional field for potential misplacement of data as well. We have previously considered and discussed adding distribution data for health regions, but decided against it for these reasons - mostly because so few health regions release that data. Much of what we do with data is dependent on the data that is actually released, which is why many of the issues you opened cannot be implemented.

I'm glad to see you're able to use the data, and adjust its format to fit your needs. Although it may not seem like it, we are open to suggestions and potential additions, though we must consider and discuss the implications all the way through to our manual data collection process. 

Looking through your link, it seems you're desiring a more broad "summary" endpoint and a different date format. These are both things that can be easily added if requested (though carefully with the date format so as not to break anything for current API users). In regards to population data, it is best to source that through StatsCan or provincially with the reporting zones for COVID-19 data as these values will change and more demographic data may become available. However, including _estimates_ (and ensuring they are considered as such) for population in our /regions endpoint would also be a reasonable (and possible) addition. 

If you have additional or specific suggestions or questions, please feel free to reach out to me via email (linked on the footer of the site) and I'd be happy to discuss potential additions to the schema and their feasibility with data availability in more detail.
