### ISSUE TITLE
Adding split health region reports

### ISSUE THREAD

**Issue by jy2wong** [andrewthong/covid19tracker-api#88]
Hi! I'm trying to add more fine-grained Canadian data to https://github.com/microcovid/microcovid and thought your API would be perfect!

For our intake, we need about 2 weeks worth of reports from each health region, a couple times a week. However, since I can't find a way to get all the health region reports together, I'm left making ~100 separate API calls for every single individual health region.

Would it be possible to allow split reports? I'd love to be able to use the following:

```
curl 'https://api.covid19tracker.ca/reports/regions/split'
```

**Comment by andrewthong** [comment]
Having a report with all dates ends up being a rather large request but if it's recent two-weeks I might be able to get you something suitable for this to minimize your calls. Let me get back to you on this.

**Comment by jy2wong** [comment]
(if it matters, it's actually 15 days of data.)

Thank you!

**Comment by blanchardjeremy** [comment]
Hi there. I'm on the same project team as @jy2wong and just wanted to hop in and second this request. We can't seem to consistently get around your API throttling issues because of how the API is structured. 

You can see the issue this causes in our log output here: https://github.com/microcovid/microcovid/runs/3392331359?check_suite_focus=true#step:7:35

We get to 62 calls and then get an error which we can't overcome.

I can get it to work locally by running the script once, caching all the results, waiting a while, then running it again and skipping over the first 62 because they are already in the cache. But I can't get GitHub actions to do the same thing because it is creating a fresh environment each time it runs the action.

If you could help us out on this, it would be greatly appreciated!

**Comment by andrewthong** [comment]
Haven't done any documentation on it but give this endpoint a try, https://devapi.covid19tracker.ca/reports/health-regions/recent
